{% set name = "patchy" %}
{% set version = "2.5.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/patchy-{{ version }}.tar.gz
  sha256: 6ebbea1a7b34acde8d5af7e370a6276b41e2607ca1742a0f8a50767b0124d3b1

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - pkgutil-resolve-name
    - python >=3.6

test:
  imports:
    - patchy
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/adamchainz/patchy
  summary: Patch the inner source of python functions at runtime.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
