{% set name = "patchy" %}
{% set version = "2.6.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/patchy-{{ version }}.tar.gz
  sha256: c71e99242c9d2467143d5b8200459e5a2e848608c7cfb7a35121f1744979de8a

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - pkgutil-resolve-name
    - python >=3.7

test:
  imports:
    - patchy
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/adamchainz/patchy
  summary: Patch the inner source of python functions at runtime.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
