{% set name = "patchy" %}
{% set version = "2.10.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/patchy-{{ version }}.tar.gz
  sha256: e7dc3610d20b8ce30af2ddbfa4a1ed67f066269fa6b10094f16dc798b80119da

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools >=77
  run:
    - python >={{ python_min }}

test:
  imports:
    - patchy
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/adamchainz/patchy
  summary: Patch the inner source of python functions at runtime.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
