{% set name = "patchy" %}
{% set version = "2.6.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/patchy-{{ version }}.tar.gz
  sha256: 8fb3400aa2c2e94dd95381731ab1d0af3b654f72417f39914858778502c4cc64

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - pkgutil-resolve-name
    - python >=3.7

test:
  imports:
    - patchy
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/adamchainz/patchy
  summary: Patch the inner source of python functions at runtime.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
